Task_1_5_2
justProductAnalyst/OOP pull request #11
Opened 2023-12-16 05:47 UTC by justProductAnalyst

2023-12-20 17:19 UTC, galinabykova requested changes

2023-12-20 17:19 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
> +            } else if (cmd.hasOption("rm")) {
как будет работать твоя программа, если ей на вход передать несколько ключевых слов, например

> notebook -add "Title" "content" -rm

?

2023-12-20 17:19 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/Note.java
> +    private static final long serialVersionUID = 1L;
расскажи, зачем нужно это поле

2023-12-20 17:19 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
> +    public static void executeCommand(
мне не нравится этот метод. Здесь ты разбираешь аргументы командной строки и выполняешь некоторую "полезную" работу (сериализуешь, выводишь строчки). Функция большая, и в ней сложно разобраться, нужно думать, к чему относится каждая строчка, к разбору аргументов или к "полезной" работе. Лучше отделить "полезную" работу так, чтобы в этой функции ты максимум вызывал методы "Вывести по ключевым словам", "Добавить заметку" и т.д., а "полезная" работа была отделена

2023-12-26 12:15 UTC, Vyacheslav-Vetrov commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
> +            } else if (cmd.hasOption("rm")) {
Они будут выполняться все последовательно, исправляю

2023-12-26 12:28 UTC, Vyacheslav-Vetrov commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
> +            } else if (cmd.hasOption("rm")) {
Она обработает только add, что не очень хорошо. Поправил это вместе с рефакторингом executeCommand

2023-12-26 12:31 UTC, Vyacheslav-Vetrov commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/Note.java
> +    private static final long serialVersionUID = 1L;
Это поле нужно для того, чтобы Java Runtime мог убедиться, что объект который он десериализует совместим с тем, который был сериализован.
Когда объект сериализуется, serialVersionUID записывается вместе с данными. При десериализации JVM сравнивает serialVersionUID сериализованного объекта с serialVersionUID текущей версии класса. Если идентификаторы не совпадают, то значит класс изменился с момента сериализации объекта, и JVM выдаст исключение

2023-12-26 12:31 UTC, Vyacheslav-Vetrov commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
> +    public static void executeCommand(
Fixed

2023-12-26 15:24 UTC, galinabykova approved these changes

2023-12-26 15:24 UTC, galinabykova commented on Task_1_5_2/src/main/java/ru/nsu/vetrov/CommandLineInterface.java
мне кажется, у тебя этот класс не совсем CommandLineInterface и точно не интерфейс, но это так мелочи)

2023-12-28 12:21 UTC, merged