Task_1_1_1
justProductAnalyst/OOP pull request #2
Opened 2023-09-13 10:09 UTC by justProductAnalyst

2023-09-14 14:24 UTC, galinabykova requested changes

2023-09-14 14:24 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/vetrov/HeapSort.java
> +        int l = 2 * i + 1;
хочется названий переменных, по которым можно сказать, что это за переменная

2023-09-14 14:24 UTC, galinabykova commented on Task_1_1_1/src/main/java/ru/nsu/vetrov/HeapSort.java
> +            heapify(arr, n, largest);
может ли здесь возникуть проблема из-за рекурсии?

2023-09-14 15:20 UTC, justProductAnalyst commented on Task_1_1_1/src/main/java/ru/nsu/vetrov/HeapSort.java
> +        int l = 2 * i + 1;
Понял, переименую.

2023-09-14 15:23 UTC, justProductAnalyst commented on Task_1_1_1/src/main/java/ru/nsu/vetrov/HeapSort.java
> +            heapify(arr, n, largest);
Гипотетически да, но только при очень большой длине массива для сортировки. В целом проблем быть не должно, так как сложность алгоритма O(log n), потому что высота дерева будет O(log n), соответственно и рекурсивных вызовов будет столько же. А это значит что даже при больших n вызовов будет не так уж много

2023-09-18 06:34 UTC, galinabykova approved these changes
на защите надо будет рассказать про пирамидальную сортировку

2023-09-18 14:39 UTC, merged