Task_1_1_2
justProductAnalyst/OOP pull request #3
Opened 2023-09-26 04:06 UTC by justProductAnalyst

Работа над задачей еще не окончена: надо добавить javadoc

2023-09-26 05:34 UTC, galinabykova requested changes

2023-09-26 05:34 UTC, galinabykova commented on Task_1_1_1/.idea/gradle.xml
убери файлики из директории .idea или докажи, что они нужны

2023-09-26 05:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +        this.coefficients = coefficients;
как передаются данные в этот конструктор: по значению или по ссылке? что будет, если изменить массив, переданный в конструктор полинома, после создания полинома?

2023-09-26 05:34 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +    public boolean equals(Object obj) {
при переопределении equals нужно переопределить hashCode
https://javarush.com/groups/posts/3957-kofe-breyk-168-zachem-pereopredeljatjh-metodih-equals-i-hashcode-v-java

2023-09-26 05:34 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/vetrov/PolynomialTest.java
> +        assertEquals("7x^3 + 6x^2 + 19x + 6", result.toString());
надо сравнивать объекты класса полином, а не строчки. После того, как ты переопределил equals, оно должно завестись

2023-09-26 05:34 UTC, galinabykova commented on Task_1_1_2/src/test/java/ru/nsu/vetrov/PolynomialTest.java
больше тестов! нужно на каждую операцию хотя бы парочку, со всякими краевыми случаями и т.д.

2023-09-30 07:26 UTC, justProductAnalyst commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +        this.coefficients = coefficients;
По значению. Если изменить массив после создания, то коэффициенты у экземпляра класса также изменятся

2023-09-30 08:09 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +        this.coefficients = coefficients;
Второе предложение верно, но это называется по ссылке. По значению - это если бы массив полностью был скопирован при передаче в конструктор и был новым объектом, никак не связанным с исходным. По значению передаются примитивные типы в Java. Массив это ссылочный тип, он передаётся по ссылке

2023-10-03 12:06 UTC, justProductAnalyst commented on Task_1_1_1/.idea/gradle.xml
Убрал

2023-10-03 12:06 UTC, justProductAnalyst commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +    public boolean equals(Object obj) {
Переопределил

2023-10-03 12:07 UTC, justProductAnalyst commented on Task_1_1_2/src/test/java/ru/nsu/vetrov/PolynomialTest.java
> +        assertEquals("7x^3 + 6x^2 + 19x + 6", result.toString());
Переделал

2023-10-03 12:07 UTC, justProductAnalyst commented on Task_1_1_2/src/test/java/ru/nsu/vetrov/PolynomialTest.java
Добавил тесты

2023-10-04 03:31 UTC, galinabykova requested changes
reviewdog

2023-10-04 03:31 UTC, galinabykova commented on Task_1_1_2/src/main/java/ru/nsu/vetrov/Polynomial.java
> +        this.coefficients = coefficients;
Лучше сделать копирование массива, потому что вот это "Если изменить массив после создания, то коэффициенты у экземпляра класса также изменятся" может много поломать

2023-10-04 16:00 UTC, galinabykova requested changes
reviewdog

2023-10-04 16:12 UTC, galinabykova approved these changes

2023-10-14 10:38 UTC, merged