Task_1_4_1
justProductAnalyst/OOP pull request #8
Opened 2023-11-21 12:08 UTC by justProductAnalyst

2023-11-21 18:04 UTC, galinabykova requested changes

2023-11-21 18:04 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +        long excellentGradesCount = grades.stream()
кажется, у тебя здесь берутся все оценки, а нужно только последние по каждому предмету

2023-11-21 18:04 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +    public void addGrade(int grade, String subject, int semester) {
Кажется, тут можно создать Grade с оценкой -1. Это нехорошо, нужно проверять границы либо здесь, либо в конструкторе Grade

2023-11-22 07:16 UTC, j4stV commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +    public void addGrade(int grade, String subject, int semester) {
Fixed

2023-11-22 07:16 UTC, justProductAnalyst commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +        long excellentGradesCount = grades.stream()
Fixed

2023-11-22 07:40 UTC, galinabykova requested changes

2023-11-22 07:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +        for (Grade grade : grades) {
преобразуй это for с использованием StreamAPI. В преобразованной версии не должно быть for и forEach. Наверно, тебе понадобится collect

2023-11-22 07:40 UTC, galinabykova commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +    private static class Grade {
почему ты решил делать nested класс?

2023-11-22 08:38 UTC, justProductAnalyst commented on Task_1_4_1/src/main/java/ru/nsu/vetrov/GradeBook.java
> +    private static class Grade {
Мне кажется это логичным решением с точки зрения организации кода и его читабельности. Потому что оценка (то есть Grade) не имеет особо смысла вне контекста зачетки. Ну и инкапсуляция таким образом получается

2023-11-22 08:46 UTC, galinabykova approved these changes

2023-11-22 14:46 UTC, merged